In [1]:
import skbeam.core.mask as mask
import skbeam.core.speckle as speckle
import skbeam.core.roi as roi

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

In [2]:
images = []
for i in range(5):
        int_array = np.tril((i + 2) * np.ones(10))
        int_array[int_array == 0] = (i + 1)
        images.append(int_array)

images_sets = [np.asarray(images), ]
roi_data = np.array(([4, 2, 2, 2], [0, 5, 4, 4]), dtype=np.int64)
label_array = roi.rectangles(roi_data, shape=images[0].shape)

prob_k_all, std = speckle.xsvs(images_sets, label_array, timebin_num=2,
                                number_of_img=5, max_cts=None)

0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working


/Users/sameera/mc/envs/work/lib/python2.7/site-packages/numpy/core/numeric.py:294: FutureWarning: in the future, full(3, 2) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
/Users/sameera/mc/envs/work/lib/python2.7/site-packages/numpy/lib/function_base.py:286: RuntimeWarning: invalid value encountered in true_divide
  return n/db/n.sum(), bins


In [3]:
prob_k_all.shape

(3, 2)

In [4]:
images_sets

[array([[[ 2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.],
         [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]],
 
        [[ 3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.,  2.,  2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.,  3.,  2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.,  3.,  3.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  

In [5]:
# testing for bad images
bad_list = []
# convert each bad image to np.nan array
images = mask.bad_to_nan_gen(images_sets, bad_list)

In [6]:
for y in images:
    print (y)

[[[ 2.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[ 3.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 3.  3.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 3.  3.  3.  2.  2.  2.  2.  2.  2.  2.]
  [ 3.  3.  3.  3.  2.  2.  2.  2.  2.  2.]
  [ 3.  3.  3.  3.  3.  2.  2.  2.  2.  2.]
  [ 3.  3.  3.  3.  3.  3.  2.  2.  2.  2.]
  [ 3.  3.  3.  3.  3.  3.  3.  2.  2.  2.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  2.  2.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  2.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]]

 [[ 4.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 4.  4.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 4.  4.  4.  3.  3.  3.  

In [7]:
new_prob_k, new_std = speckle.xsvs(images, label_array, timebin_num=2,
                                    number_of_img=5, max_cts=6)

In [8]:
new_prob_k

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=object)

In [9]:
imgs = []
for i in range(10):
        int_array = np.tril((i + 2) * np.ones(10))
        int_array[int_array == 0] = (i + 1)
        imgs.append(int_array)

# testing for bad images
bad_list = [5, 7]
# convert each bad image to np.nan array
images1 = mask.bad_to_nan_gen(imgs, bad_list)

In [10]:
images1

<generator object bad_to_nan_gen at 0x1038ad0a0>

In [11]:
#for y in images1:
#    print (y)

In [12]:
new_prob_k, new_std = speckle.xsvs((images1, ), label_array, timebin_num=2,
                                    number_of_img=5, max_cts=6)

0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
working
0.0
not_working
1.0
0.0
not_working
1.0
0.0
not_working
1.0
1.0
working
1.0
not_working
2.0
1.0
not_working
2.0
1.0
not_working
2.0
2.0
not_working
3.0
2.0
not_working
3.0
2.0
working
3.0
not_working
4.0
3.0
not_working
4.0
2.0
working
4.0
working
4.0
not_working
5.0


In [17]:
new_prob_k

array([[array([ 0.   ,  0.   ,  0.125,  0.125,  0.25 ]),
        array([ 0.   ,  0.125,  0.125,  0.125,  0.25 ])],
       [ array([ 0.        ,  0.        ,  0.16666667,  0.        ,  0.        ,
        0.16666667,  0.        ,  0.16666667,  0.        ,  0.16666667,
        0.16666667]),
        array([ 0.        ,  0.16666667,  0.        ,  0.16666667,  0.        ,
        0.16666667,  0.        ,  0.16666667,  0.        ,  0.16666667,  0.        ])],
       [ array([ 0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0. ,  0.2,  0. ,  0. ,  0. ,
        0. ,  0.2,  0. ,  0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0.2,  0. ,
        0. ]),
        array([ 0. ,  0.2,  0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0.2,  0. ,  0. ,
        0. ,  0.2,  0. ,  0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ])]], dtype=object)

In [18]:
prob_k_all

array([[array([ 0. ,  0. ,  0.2,  0.2,  0.4]),
        array([ 0. ,  0.2,  0.2,  0.2,  0.4])],
       [array([ 0. ,  0. ,  0.2,  0. ,  0. ,  0.2,  0. ,  0.2,  0. ,  0.2,  0.2]),
        array([ 0. ,  0.2,  0. ,  0.2,  0. ,  0.2,  0. ,  0.2,  0. ,  0.2,  0. ])],
       [ array([ 0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0. ,  0.2,  0. ,  0. ,  0. ,
        0. ,  0.2,  0. ,  0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0.2,  0. ,
        0. ]),
        array([ 0. ,  0.2,  0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0.2,  0. ,  0. ,
        0. ,  0.2,  0. ,  0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ])]], dtype=object)

In [15]:
from numpy.testing import (assert_array_almost_equal,
                           assert_almost_equal)


In [16]:
assert_array_almost_equal(new_prob_k[0, 0],
                              np.array([0., 0., 0.2, 0.2, 0.4]))
assert_array_almost_equal(new_prob_k[0, 1],
                              np.array([0., 0.2, 0.2, 0.2, 0.4]))


In [17]:
def get_qedge( qstart,qend,qwidth,noqs,  ):
    ''' DOCUMENT make_qlist( )
    give qstart,qend,qwidth,noqs
    return a qedge by giving the noqs, qstart,qend,qwidth.
           a qcenter, which is center of each qedge 
    KEYWORD:  None    ''' 
    import numpy as np 
    qcenter = np.linspace(qstart,qend,noqs)
    #print ('the qcenter is:  %s'%qcenter )
    qedge=np.zeros(2*noqs) 
    qedge[::2]= (qcenter - (qwidth/2)  ) #+1  #render  even value
    qedge[1::2]= (qcenter + qwidth/2) #render odd value
    return qedge, qcenter    

In [93]:
qstart = 2
qend=30
qwidth=2
noqs=4

qedge, qcenter = get_qedge(qstart, qend, qwidth, noqs)

In [94]:
qedge

array([  1.        ,   3.        ,  10.33333333,  12.33333333,
        19.66666667,  21.66666667,  29.        ,  31.        ])

In [95]:
qcenter

array([  2.        ,  11.33333333,  20.66666667,  30.        ])

In [96]:
import skbeam.core.roi as roi

In [98]:
qcenter = np.linspace(qstart,qend,noqs)

In [99]:
edge = roi.ring_edges(qstart, qend, qwidth, noqs)

In [100]:
edge


array([[   2.,   32.],
       [  34.,   64.],
       [  66.,   96.],
       [  98.,  128.]])

In [102]:
edge = roi.ring_edges(qstart, qwidth, num_rings=noqs)

In [103]:
edge

array([[  2.,   4.],
       [  4.,   6.],
       [  6.,   8.],
       [  8.,  10.]])

## Following get_qmap_label is same as ring_roi in roi.py

In [104]:
def get_qmap_label( qmap, qedge ):
    import numpy as np
    '''give a qmap and qedge to bin the qmap into a label array'''
    edges = np.atleast_2d(np.asarray(qedge)).ravel()
    label_array = np.digitize(qmap.ravel(), edges, right=False)
    label_array = np.int_(label_array)
    label_array = (np.where(label_array % 2 != 0, label_array, 0) + 1) // 2
    label_array = label_array.reshape( qmap.shape )
    return label_array


In [106]:
#?? have to think about qend
def get_qedge( qstart,qend,qwidth,noqs,  ):
    ''' DOCUMENT make_qlist( )
    give qstart,qend,qwidth,noqs
    return a qedge by giving the noqs, qstart,qend,qwidth.
           a qcenter, which is center of each qedge
    KEYWORD:  None    '''
    import numpy as np
    qcenter = np.linspace(qstart,qend,noqs)
    #print ('the qcenter is:  %s'%qcenter )
    qedge=np.zeros(2*noqs)
    qedge[::2]= (  qcenter- (qwidth/2)  ) #+1  #render  even value
    qedge[1::2]= ( qcenter+ qwidth/2) #render odd value
    return qedge, qcenter