In [1]:
import numpy as np
import skbeam.core.utils as utils
import skbeam.core.roi as roi
import itertools

In [2]:
num_levels = 1
num_bufs = 10
# must be even
xdim = 80
ydim = 80
stack_size = 10
synthetic_data = np.random.randint(1, 10, (stack_size, xdim, ydim))

rois = np.zeros_like(synthetic_data[0])
# make sure that the ROIs can be any integers greater than 1. They do not
# have to start at 1 and be continuous
rois[0:xdim//10, 0:ydim//10] = 5
rois[xdim//10:xdim//5, ydim//10:ydim//5] = 3

##  Orginal time corrleation code check the delay no and buf no 
##### print ("delay_no", delay_no, buf_no)

In [3]:
import skbeam.core.correlation as corr
#(num_levels, num_bufs, labels, images)
corr_gen = corr.multi_tau_auto_corr(num_levels, num_bufs, rois, synthetic_data)

In [4]:
corr_gen[1], corr_gen[0]

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 array([[ 1.26495475,  1.2639415 ],
        [ 0.98458881,  1.00551669],
        [ 1.01332308,  0.98678808],
        [ 0.99724132,  0.99473262],
        [ 1.00362894,  0.98560929],
        [ 0.99262339,  0.97557246],
        [ 1.00689655,  0.99460518],
        [ 0.98736845,  0.97213712],
        [ 0.96295299,  0.99578059],
        [ 1.02117196,  0.95459602]]))

In [5]:
synthetic_data[0].shape

(80, 80)

In [6]:
num_levels = 1
num_bufs=2
corr_gen = corr.multi_tau_auto_corr(num_levels, num_bufs, rois, synthetic_data[:2])

In [7]:
corr_gen[0]

array([[ 1.27289632,  1.24979971],
       [ 1.03771503,  0.94865144]])

In [8]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
y = 