In [1]:
import numpy as np
import skbeam.core.utils as utils
import skbeam.core.roi as roi
import itertools

In [4]:
num_levels = 1
num_bufs = 10
# must be even
xdim = 80
ydim = 80
stack_size = 10
synthetic_data = np.random.randint(1, 10, (stack_size, xdim, ydim))

rois = np.zeros_like(synthetic_data[0])
# make sure that the ROIs can be any integers greater than 1. They do not
# have to start at 1 and be continuous
rois[0:xdim//10, 0:ydim//10] = 5
rois[xdim//10:xdim//5, ydim//10:ydim//5] = 3

##  Orginal time corrleation code check the delay no and buf no 
##### print ("delay_no", delay_no, buf_no)

In [5]:
import skbeam.core.correlation as corr
#(num_levels, num_bufs, labels, images)
corr_gen = corr.multi_tau_auto_corr(num_levels, num_bufs, rois, synthetic_data)

+++++++++++++++++++++++++++++
t_index 0.0
delay_no 1 1
arr [ 36.234375  31.453125]
arr [ 5.546875  4.953125]
arr [ 5.546875  4.953125]
+++++++++++++++++++++++++++++
t_index 0.0
delay_no 2 2
arr [ 34.015625  31.390625]
arr [ 5.296875  5.015625]
arr [ 5.296875  5.015625]
t_index 1.0
delay_no 1 2
arr [ 27.203125  25.5625  ]
arr [ 5.546875  4.953125]
arr [ 5.046875  5.078125]
+++++++++++++++++++++++++++++
t_index 0.0
delay_no 3 3
arr [ 32.296875    28.94791667]
arr [ 5.078125  4.78125 ]
arr [ 5.078125  4.78125 ]
t_index 1.0
delay_no 2 3
arr [ 25.40625  23.6875 ]
arr [ 5.296875  5.015625]
arr [ 4.84375    4.6953125]
t_index 2.0
delay_no 1 3
arr [ 24.546875  21.203125]
arr [ 5.546875  4.953125]
arr [ 4.640625  4.3125  ]
+++++++++++++++++++++++++++++
t_index 0.0
delay_no 4 4
arr [ 31.39453125  30.78515625]
arr [ 5.02734375  4.92578125]
arr [ 5.02734375  4.92578125]
t_index 1.0
delay_no 3 4
arr [ 24.61979167  23.29166667]
arr [ 5.078125  4.78125 ]
arr [ 4.85416667  4.91666667]
t_index 2.0
dela

In [9]:
corr_gen[1], corr_gen[0]

(array([ 0,  1,  2,  3,  4,  6,  8, 12, 16, 24]),
 array([[ 1.27352577,  1.27292353],
        [ 0.99905194,  1.00266755],
        [ 1.00978057,  0.99609001],
        [ 1.00309406,  1.00046825],
        [ 1.00710429,  1.00142976],
        [ 1.00150032,  0.99610916],
        [ 1.00068922,  0.99938757],
        [ 1.00082129,  1.00321251],
        [ 1.00236425,  1.00055308],
        [ 0.9989169 ,  0.99903947]]))

In [11]:
synthetic_data[0].shape

(80, 80)

In [16]:
num_levels = 1
num_bufs=2
corr_gen = corr.multi_tau_auto_corr(num_levels, num_bufs, rois, synthetic_data[:2])

t_index 0.0
arr [ 33.09375   28.046875]
arr [ 5.21875   4.671875]
arr [ 5.21875   4.671875]
t_index 0.0
arr [ 34.0625     26.2265625]
arr [ 5.28125    4.5078125]
arr [ 5.28125    4.5078125]
t_index 1.0
arr [ 29.     19.125]
arr [ 5.21875   4.671875]
arr [ 5.34375  4.34375]


In [17]:
corr_gen[0]

array([[ 1.22124575,  1.29065356],
       [ 1.03988514,  0.94242198]])

In [7]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])