In [4]:
import numpy as np


In [5]:
def delays( num_lev=3, num_buf=4, time=1 ): 
    ''' DOCUMENT delays(time=)
        return array of delays.
        KEYWORD:  time: scale delays by time ( should be time between frames)
     '''
    if num_buf%2!=0:print ("nobuf must be even!!!"    )
    dly=np.zeros( (num_lev+1)*int(num_buf/2) +1  )        
    dict_dly ={}
    for i in range( 1,num_lev+1):
        if i==1:imin= 1
        else:imin= int(num_buf/2)+1
        ptr=(i-1)*int(num_buf/2)+ np.arange(imin,num_buf+1)
        dly[ptr]= np.arange( imin, num_buf+1) *2**(i-1)            
        dict_dly[i] = dly[ptr-1]            
        dly*=time
        #print (i, ptr, imin)
    return dly, dict_dly


In [6]:
dly, dict_dly = delays(2, 4, 1)

In [7]:
dly

array([ 0.,  1.,  2.,  3.,  4.,  6.,  8.])

In [8]:
dict_dly

{1: array([ 0.,  1.,  2.,  3.]), 2: array([ 4.,  6.])}

In [9]:
def multi_tau_lags(multitau_levels, multitau_channels):
    """
    Standard multiple-tau algorithm for finding the lag times (delay
    times).

    Parameters
    ----------
    multitau_levels : int
        number of levels of multiple-taus
    multitau_channels : int
        number of channels or number of buffers in auto-correlators
        normalizations (must be even)

    Returns
    -------
    total_channels : int
        total number of channels ( or total number of delay times)
    lag_steps : ndarray
        delay or lag steps for the multiple tau analysis
    dict_lags : dict
        dictionary of delays for each multitau_levels

    Notes
    -----
    The multi-tau correlation scheme was used for finding the lag times
    (delay times).

    References: text [1]_

    .. [1] K. Schätzela, M. Drewela and  S. Stimaca, "Photon correlation
       measurements at large lag times: Improving statistical accuracy,"
       J. Mod. Opt., vol 35, p 711–718, 1988.
    """

    if (multitau_channels % 2 != 0):
        raise ValueError("Number of  multiple tau channels(buffers)"
                         " must be even. You provided {0} "
                         .format(multitau_channels))

    # total number of channels ( or total number of delay times)
    tot_channels = (multitau_levels + 1)*multitau_channels//2

    lag = []
    dict_lags = {}
    lag_steps = np.arange(0, multitau_channels)
    dict_lags[1] = lag_steps
    for i in range(2, multitau_levels + 1):
        each_level = []
        for j in range(0, multitau_channels//2):
            lag_value = (multitau_channels//2 + j)*(2**(i - 1))
            lag.append(lag_value)
            each_level.append(lag_value)
        dict_lags[i] = each_level

    lag_steps = np.append(lag_steps, np.array(lag))

    return tot_channels, lag_steps, dict_lags


In [10]:
tot, lags, dict_lags = multi_tau_lags(3, 4)

In [11]:
lags

array([ 0,  1,  2,  3,  4,  6,  8, 12])

In [12]:
dict_lags

{1: array([0, 1, 2, 3]), 2: [4, 6], 3: [8, 12]}

In [13]:
lags[0:4]

array([0, 1, 2, 3])

In [14]:
lags[4:6], lags[6:8]

(array([4, 6]), array([ 8, 12]))

In [15]:
lags[::2]

array([0, 2, 4, 8])

In [16]:
y = iter(lags)

In [17]:
for x in y:
    print x, next(y)

0 1
2 3
4 6
8 12


In [18]:
def multi_tau_lags(multitau_levels, multitau_channels):
    """
    Standard multiple-tau algorithm for finding the lag times (delay
    times).

    Parameters
    ----------
    multitau_levels : int
        number of levels of multiple-taus
    multitau_channels : int
        number of channels or number of buffers in auto-correlators
        normalizations (must be even)

    Returns
    -------
    total_channels : int
        total number of channels ( or total number of delay times)
    lag_steps : ndarray
        delay or lag steps for the multiple tau analysis

    Notes
    -----
    The multi-tau correlation scheme was used for finding the lag times
    (delay times).

    References: text [1]_

    .. [1] K. Schätzela, M. Drewela and  S. Stimaca, "Photon correlation
       measurements at large lag times: Improving statistical accuracy,"
       J. Mod. Opt., vol 35, p 711–718, 1988.
    """

    if (multitau_channels % 2 != 0):
        raise ValueError("Number of  multiple tau channels(buffers)"
                         " must be even. You provided {0} "
                         .format(multitau_channels))

    # total number of channels ( or total number of delay times)
    tot_channels = (multitau_levels + 1)*multitau_channels//2

    lag = []
    dict_lags = {}
    lag_steps = np.arange(0, multitau_channels)
    for i in range(2, multitau_levels + 1):
        for j in range(0, multitau_channels//2):
            lag.append((multitau_channels//2 + j)*(2**(i - 1)))
    dict_lags[1] = lag_steps
    lag_steps = np.append(lag_steps, np.array(lag))
    
    y = 1
    lag_it = iter(lag)
    for x in lag_it:
        y += 1
        dict_lags[y] = x, next(lag_it)

    return tot_channels, lag_steps, dict_lags

In [19]:
import numpy as np
def multi_tau_lags(multitau_levels, multitau_channels):
    """
    Standard multiple-tau algorithm for finding the lag times (delay
    times).

    Parameters
    ----------
    multitau_levels : int
        number of levels of multiple-taus
    multitau_channels : int
        number of channels or number of buffers in auto-correlators
        normalizations (must be even)

    Returns
    -------
    total_channels : int
        total number of channels ( or total number of delay times)
    lag_steps : ndarray
        delay or lag steps for the multiple tau analysis
    dict_lags : dict
        dictionary of delays for each multitau_levels

    Notes
    -----
    The multi-tau correlation scheme was used for finding the lag times
    (delay times).

    References: text [1]_

    .. [1] K. Schätzela, M. Drewela and  S. Stimaca, "Photon correlation
       measurements at large lag times: Improving statistical accuracy,"
       J. Mod. Opt., vol 35, p 711–718, 1988.
    """

    if (multitau_channels % 2 != 0):
        raise ValueError("Number of  multiple tau channels(buffers)"
                         " must be even. You provided {0} "
                         .format(multitau_channels))

    # total number of channels ( or total number of delay times)
    tot_channels = (multitau_levels + 1)*multitau_channels//2

    lag = []
    dict_lags = {}
    lag_steps = np.arange(0, multitau_channels)
    dict_lags[1] = lag_steps
    for i in range(2, multitau_levels + 1):
        y = []
        for j in range(0, multitau_channels//2):
            value = (multitau_channels//2 + j)*(2**(i - 1))
            lag.append(value)
            y.append(value)
        dict_lags[i] = np.asarray(y)

    
    lag_steps = np.append(lag_steps, np.array(lag))

    return tot_channels, lag_steps, dict_lags

In [20]:
tot, lags, dict_lags = multi_tau_lags(5, 8)
lags
dict_lags

{1: array([0, 1, 2, 3, 4, 5, 6, 7]),
 2: array([ 8, 10, 12, 14]),
 3: array([16, 20, 24, 28]),
 4: array([32, 40, 48, 56]),
 5: array([ 64,  80,  96, 112])}

In [21]:
lags[4:6], lags[6:8]

(array([4, 5]), array([6, 7]))

In [22]:
tot, lags, dict_lags = multi_tau_lags(4, 16)
lags

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  18,  20,  22,  24,  26,  28,  30,  32,  36,
        40,  44,  48,  52,  56,  60,  64,  72,  80,  88,  96, 104, 112, 120])

In [25]:
lags[16: 16+(16/2)], lags[16+16/2: ]

(array([16, 18, 20, 22, 24, 26, 28, 30]),
 array([ 32,  36,  40,  44,  48,  52,  56,  60,  64,  72,  80,  88,  96,
        104, 112, 120]))

In [26]:
tot, lags, dict_lags = multi_tau_lags(3, 8)

In [27]:
lags[8:8 +8/2], lags[12:8+8]

(array([ 8, 10, 12, 14]), array([16, 20, 24, 28]))

In [28]:
dict_lags

{1: array([0, 1, 2, 3, 4, 5, 6, 7]),
 2: array([ 8, 10, 12, 14]),
 3: array([16, 20, 24, 28])}

In [29]:

Num= {key: [0]* len(dict_lags[key]) for key in list(dict_lags.keys())}

In [30]:
Num

{1: [0, 0, 0, 0, 0, 0, 0, 0], 2: [0, 0, 0, 0], 3: [0, 0, 0, 0]}

In [31]:
imin = 1
num_buf = 8
num_lev =3
dly=np.zeros( (num_lev+1)*int(num_buf/2) +1  ) 
for i in range(1,num_lev+1):
        if i==1:
            imin = 1
        else:
            imin = int(num_buf/2) + 1
        ptr = (i-1)*int(num_buf/2) + np.arange(imin-1, num_buf)
        dly[ptr]= np.arange(imin-1, num_buf) *2**(i-1)
        print dly[ptr]

[ 0.  1.  2.  3.  4.  5.  6.  7.]
[  8.  10.  12.  14.]
[ 16.  20.  24.  28.]


In [32]:
import skbeam.core.utils as core

In [33]:
from numpy.testing import (assert_array_equal, assert_array_almost_equal,
                           assert_almost_equal)
import sys
levels = 3
channels = 8

delay_steps = [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 20, 24, 28]
#dict_dly[1] = (0, 1, 2, 3, 4, 5, 6, 7)
#dict_dly[3] = (16, 20, 24, 28)

tot_channels, lag_steps, dict_lags  = core.multi_tau_lags(levels, channels)

assert_array_equal(16, tot_channels)
assert_array_equal(delay_steps, lag_steps)


In [34]:
lag_steps

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 12, 14, 16, 20, 24, 28])

In [35]:
dict_lags

{1: array([0, 1, 2, 3, 4, 5, 6, 7]), 2: [8, 10, 12, 14], 3: [16, 20, 24, 28]}

In [36]:
dict_dly = {}
dict_dly[1] = (0, 1, 2, 3, 4, 5, 6, 7)
dict_dly[3] = (16, 20, 24, 28)
dict_dly[2] = (8, 10, 12, 14)

assert_array_equal(16, tot_channels)
assert_array_equal(delay_steps, lag_steps)
assert_array_almost_equal(dict_dly[1], dict_lags[1])
assert_array_almost_equal(dict_dly[3], dict_lags[3])