In [1]:
import skbeam.core.roi as roi 
import skbeam.core.correlation as corr
import skbeam.core.utils as utils

import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.ticker import MaxNLocator
from matplotlib.colors import LogNorm

In [2]:
num_levels = 1
num_bufs = 10  # must be even
xdim = 10
ydim = 10
stack_size = 10
img_stack = np.random.randint(1, 3, (stack_size, xdim, ydim))
rois = np.zeros_like(img_stack[0])
# make sure that the ROIs can be any integers greater than 1. They do not
# have to start at 1 and be continuous
rois[0:xdim//10, 0:ydim//10] = 5
rois[xdim//10:xdim//5, ydim//10:ydim//5] = 3

In [24]:
def bad_nan_gen(image_gen, bad_list):
    """
    This function will convert the bad image array in the images into
    NAN(Not-A-Number) array

    Parameters
    ----------
    image_gen : array
        image_iterable : iterable of 2D arrays
     : list
        bad images list

    Yields
    ------
    img : array
        if image is bad it will convert to np.nan array otherwise no
        change to the array

    """
    for n, im in enumerate(image_gen):
        if n in bad_list:
            yield np.nan*np.ones_like(im)
        else:
            yield im

In [25]:
bad_list = [1, 4, 6]

In [26]:
img = mask_gen(img_stack, bad_list)

In [27]:
y = []
for result in img:
    y.append(result)

(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)
(10, 10)


In [34]:
y = np.asarray(y)
y

array([[[  1.,   2.,   1.,   1.,   1.,   2.,   2.,   1.,   2.,   1.],
        [  2.,   1.,   1.,   2.,   2.,   1.,   1.,   1.,   2.,   1.],
        [  2.,   2.,   1.,   2.,   2.,   2.,   2.,   2.,   2.,   1.],
        [  2.,   2.,   1.,   1.,   1.,   1.,   1.,   1.,   2.,   2.],
        [  1.,   1.,   1.,   2.,   1.,   1.,   2.,   2.,   2.,   2.],
        [  1.,   1.,   2.,   1.,   2.,   2.,   2.,   2.,   2.,   2.],
        [  1.,   1.,   2.,   2.,   2.,   1.,   2.,   2.,   2.,   2.],
        [  1.,   1.,   2.,   1.,   1.,   1.,   1.,   1.,   2.,   2.],
        [  2.,   1.,   2.,   2.,   1.,   2.,   2.,   2.,   2.,   2.],
        [  2.,   2.,   1.,   1.,   1.,   1.,   1.,   2.,   2.,   2.]],

       [[ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [ nan,  na

In [42]:
x = y[np.logical_not(np.isnan(y))]
x

array([ 1.,  2.,  1.,  1.,  1.,  2.,  2.,  1.,  2.,  1.,  2.,  1.,  1.,
        2.,  2.,  1.,  1.,  1.,  2.,  1.,  2.,  2.,  1.,  2.,  2.,  2.,
        2.,  2.,  2.,  1.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,
        2.,  1.,  1.,  1.,  2.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,  1.,
        2.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,  2.,  2.,  2.,
        1.,  2.,  2.,  2.,  2.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,
        2.,  2.,  2.,  1.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  1.,  2.,  1.,
        2.,  2.,  1.,  1.,  2.,  1.,  2.,  1.,  2.,  2.,  2.,  2.,  1.,
        2.,  2.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  1.,  2.,  2.,  2.,
        1.,  1.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        1.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,  1.,  2.,
        1.,  2.,  1.,  2.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  2.,  2.,
        1.,  1.,  2.,  1.,  1.,  2.,  2.,  1.,  2.,  2.,  1.,  1

In [66]:
for i in y:
    if np.isnan(i.any())==False:
        print i.any()
    #if (~np.isnan(i.any())==True):
    #    print i

 True
True
True
True
True
True
True
True
True
True


In [55]:
for i in y:
    if 

(array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]], dtype=bool), True)

In [29]:
img1 = mask_gen((img_stack[0], ), [0])

In [31]:
for im in img1:
    print im

(10, 10)
[[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]]


In [7]:
y1 = np.ones((2, 2)) + np.nan*np.ones((2,2))
y2 = np.ones((2,2))

In [8]:
y1, y2

(array([[ nan,  nan],
        [ nan,  nan]]), array([[ 1.,  1.],
        [ 1.,  1.]]))

In [9]:
y1*y2

array([[ nan,  nan],
       [ nan,  nan]])

In [10]:
y0 = 10*np.ones((2, 2))

In [11]:
y0 + y1

array([[ nan,  nan],
       [ nan,  nan]])

In [12]:
y0*y1

array([[ nan,  nan],
       [ nan,  nan]])

In [13]:
~np.isnan((y1,y2, y0))

array([[[False, False],
        [False, False]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]], dtype=bool)

In [17]:
a = [1, 2, 3]
b = [4, 5, 6, 7]

zip(a, b)

[(1, 4), (2, 5), (3, 6)]

In [67]:
img_stack[0]

array([[1, 2, 1, 1, 1, 2, 2, 1, 2, 1],
       [2, 1, 1, 2, 2, 1, 1, 1, 2, 1],
       [2, 2, 1, 2, 2, 2, 2, 2, 2, 1],
       [2, 2, 1, 1, 1, 1, 1, 1, 2, 2],
       [1, 1, 1, 2, 1, 1, 2, 2, 2, 2],
       [1, 1, 2, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 2, 2, 2, 1, 2, 2, 2, 2],
       [1, 1, 2, 1, 1, 1, 1, 1, 2, 2],
       [2, 1, 2, 2, 1, 2, 2, 2, 2, 2],
       [2, 2, 1, 1, 1, 1, 1, 2, 2, 2]])

In [85]:
img_stack[0][0, 1] =100
img_stack[0][9, 1] =100
img_stack[6][8, 8] =100

In [86]:
img_stack[0]

array([[  1, 100,   1,   1,   1,   2,   2,   1,   2,   1],
       [  2,   1,   1,   2,   2,   1,   1,   1,   2,   1],
       [  2,   2,   1,   2,   2,   2,   2,   2,   2,   1],
       [  2,   2,   1,   1,   1,   1,   1,   1,   2,   2],
       [  1,   1,   1,   2,   1,   1,   2,   2,   2,   2],
       [  1,   1,   2,   1,   2,   2,   2,   2,   2,   2],
       [  1,   1,   2,   2,   2,   1,   2,   2,   2,   2],
       [  1,   1,   2,   1,   1,   1,   1,   1,   2,   2],
       [  2,   1,   2,   2,   1,   2,   2,   2,   2,   2],
       [  2, 100,   1,   1,   1,   1,   1,   2,   2,   2]])

## Getting the thershold generator thing works

In [87]:
def threshold_mask(images, threshold, ther_mask=None):
    """
    This generator will create a threshold mask for images

    Parameters
    ----------
    images : array
        image_iterable : iterable of 2D arrays
    threshold: float
        threshold value to remove the hot spots in the image

    Yields
    -------
    thre_mask : array
        image mask to remove the hot spots
    """
    if ther_mask is None:
        thre_mask = np.ones_like(images[0])
    for im in images:
        bad_pixels = np.where(im >= threshold)
        if len(bad_pixels[0])!=0:
            thre_mask[bad_pixels] = 0
        yield thre_mask

In [88]:
img_stack

array([[[  1, 100,   1,   1,   1,   2,   2,   1,   2,   1],
        [  2,   1,   1,   2,   2,   1,   1,   1,   2,   1],
        [  2,   2,   1,   2,   2,   2,   2,   2,   2,   1],
        [  2,   2,   1,   1,   1,   1,   1,   1,   2,   2],
        [  1,   1,   1,   2,   1,   1,   2,   2,   2,   2],
        [  1,   1,   2,   1,   2,   2,   2,   2,   2,   2],
        [  1,   1,   2,   2,   2,   1,   2,   2,   2,   2],
        [  1,   1,   2,   1,   1,   1,   1,   1,   2,   2],
        [  2,   1,   2,   2,   1,   2,   2,   2,   2,   2],
        [  2, 100,   1,   1,   1,   1,   1,   2,   2,   2]],

       [[  1,   1,   1,   1,   2,   2,   2,   1,   1,   1],
        [  1,   2,   1,   2,   1,   1,   2,   1,   1,   2],
        [  1,   1,   1,   1,   2,   2,   2,   1,   2,   2],
        [  2,   1,   2,   1,   1,   2,   2,   1,   1,   2],
        [  1,   2,   2,   2,   2,   1,   1,   2,   2,   1],
        [  1,   2,   2,   2,   2,   1,   2,   2,   1,   1],
        [  1,   1,   1,   1,   2,   2,

In [89]:
t = threshold_mask(img_stack, 75)

In [92]:
for u in t:
    pass
u

array([[1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1]])

In [93]:
xdim = 10
ydim = 10
stack_size = 10
img_stack = np.random.randint(1, 3, (stack_size, xdim, ydim))

img_stack[0][0, 1] = 100
img_stack[0][9, 1] = 98
img_stack[6][8, 8] = 75
img_stack[7][6, 6] = 80

th = threshold_mask(img_stack, 75)

for final in th:
        pass
    
y = np.ones_like(img_stack[0])
y[0, 1] = 0
y[9, 1] = 0
y[8, 8] = 0
y[6, 6] = 0

In [94]:
y

array([[1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1]])

In [97]:
final

array([[1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1]])

In [96]:
np.all(y==final)

False

In [98]:
final==y

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

## Get the bad image things work

In [100]:
def bad_to_nan_gen(image_gen, bad_list):
    """
    This generator will convert the bad image array in the images into
    NAN(Not-A-Number) array

    Parameters
    ----------
    image_gen : array
        image_iterable : iterable of 2D arrays
     : list
        bad images list

    Yields
    ------
    img : array
        if image is bad it will convert to np.nan array otherwise no
        change to the array
    """
    for n, im in enumerate(image_gen):
        if n in bad_list:
            yield np.nan*np.ones_like(im)
        else:
            yield im
xdim = 2
ydim = 2
stack_size = 6
img_stack = np.random.randint(1, 3, (stack_size, xdim, ydim))

bad_list = [1, 3]

img = bad_to_nan_gen(img_stack, bad_list)

y = []
for im in img:
        y.append(im)

In [101]:
np.asarray(y)

array([[[  2.,   1.],
        [  1.,   1.]],

       [[ nan,  nan],
        [ nan,  nan]],

       [[  2.,   1.],
        [  1.,   2.]],

       [[ nan,  nan],
        [ nan,  nan]],

       [[  2.,   2.],
        [  1.,   1.]],

       [[  1.,   2.],
        [  1.,   2.]]])

In [102]:
import numpy as np
from numpy.testing import assert_array_almost_equal
from nose.tools import assert_raises


In [108]:
assert (np.isnan(np.asarray(y)[1]).all()==True)
assert (np.isnan(np.asarray(y)[3]).all()==True)
assert (np.isnan(np.asarray(y)[4]).all()==False)

In [111]:
assert (np.isnan(np.asarray(y)[2]).all()==True)  to check it this should give error

AssertionError: 

In [120]:
(img_stack[1][0,0].data==0)

False